name: breast_data

channels:
  - conda-forge
  - defaults
  - pytorch

dependencies:
  - ase
  - cudatoolkit=11.7
  - googledrivedownloader
  - h5py
  - jinja2
  - networkx
  - numba
  - numpy
  - pandas
  - pip
  - python=3.8
  - python-louvain
  - pytorch=1.7
  - rdflib
  - requests
  - scikit-learn
  - scipy
  - torchaudio
  - torchvision
  - tqdm
  - bokeh
  - dask
  - dask-ml
  - dask-labextension
  - datashader
  - featuretools
  - gh
  - git
  - holoviews
  - hvplot
  - imbalanced-learn
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-lsp
  - lightgbm
  - matplotlib
  - optuna
  - pandas
  - panel
  - pip:
    - -r requirements.txt
  - pyarrow
  - python
  - python-language-server
  - pyviz_comms
  - scikit-learn
  - scipy
  - shap
  - umap-learn
  - wandb
  - xarray
  - xeus-python
  - xgboost
